# App Configuration
APP_NAME:
APP_ENV:
LOG_LEVEL:
SERVER_PORT:
READ_TIMEOUT_MS:
WRITE_TIMEOUT_MS:
APP_VERSION:

LIVE_LIMIT:

# Database Configuration
DB_NAME:
SSL_MODE:
DB_HOST:
DB_USER:
DB_PASSWORD:
DB_PORT:
DB_POOL_SIZE:
DB_READ_TIMEOUT:
DB_WRITE_TIMEOUT:
DB_CONNECTION_MAX_LIFETIME_MINUTE:

# Database Appier Configuration
DB_NAME_APPIER:
SSL_MODE_APPIER:
DB_HOST_APPIER:
DB_USER_APPIER:
DB_PASSWORD_APPIER:
DB_PORT_APPIER:
DB_POOL_SIZE_APPIER:
DB_READ_TIMEOUT_APPIER:
DB_WRITE_TIMEOUT_APPIER:
DB_CONNECTION_MAX_LIFETIME_MINUTE_APPIER:

# Redis Configuration
CACHE_HOST:
CACHE_POOL_SIZE:
CACHE_DIAL_TIMEOUT:
CACHE_READ_TIMEOUT:
CACHE_WRITE_TIMEOUT:
CACHE_IDLE_TIMEOUT:
CACHE_DB:
CACHE_MX_LOOKUP_TTL_MINUTES:
CACHE_INVALID_MX_LOOKUP_TTL_MINUTES:
CACHE_PASSWORD:
CACHE_API_TIMEOUT:

# APM Configuration
ELASTIC_APM_ACTIVE:
ELASTIC_APM_API_KEY:
ELASTIC_APM_ENVIRONMENT:
ELASTIC_APM_SERVER_URL:
ELASTIC_APM_SERVICE_NAME:


