# App Configuration
APP_NAME:
APP_ENV:
LOG_LEVEL:
SERVER_PORT:
READ_TIMEOUT_MS:
WRITE_TIMEOUT_MS:
APP_VERSION:

# Database Configuration
DB_NAME:
SSL_MODE:
DB_HOST:
DB_USER:
DB_PASSWORD:
DB_PORT:
DB_POOL_SIZE:
DB_READ_TIMEOUT:
DB_WRITE_TIMEOUT:
DB_CONNECTION_MAX_LIFETIME_MINUTE:


